version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: my-postgres
    env_file: ./.env
    volumes:
      - "~/postgresdata:/var/lib/postgresql/data"
    networks:
      - mynetwork
    ports:
      - "5433:5432"
    restart: unless-stopped

networks:
  mynetwork:
    driver: bridge
